### ISSUE TITLE
Custom Events + "User Journey" Deep Dive 👤 📈 🔍 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-analytics#11]
# Story

As an engineer building a web-based software product, 
I would like to **log _custom_ events** per unique ***session*** to the `Analytics` backend
**So that** I can **_visualise_** the "***User Journey***" in _same_ interface as all other `Analytics` events/data (page views, etc.)

As noted in https://github.com/dwyl/learn-analytics/issues/11#issuecomment-2345486960 ⬇️ the stats collected by ("Plausible Community Edition") are "basic".
> Hence forth referred to as just "_Analytics_" because _nobody_ (outside of a _microscopic_ group of hackers) has heard of "Plausible" and "Community Edition" raises unnecessary _time-wasting questions_!
Obviously we will continue to give "Plausible Co" full credit and continue to [_sponsor_](https://github.com/sponsors/plausible) their efforts. 
But the _branding_ is important for internal and external (client) discussions and _everyone_ knows "Analytics". 

# Todo  

+ [x] Create a `custom-events.md` file in this repo where we will document all knowledge acquired. 📝 
+ [x] ***Transfer*** the initial ["Exploring Custom Events"](https://github.com/dwyl/learn-analytics/tree/e61fe333888141410ad1f6f9366ffd08ad962b97/plausible#4-exploring-custom-events-in-plausible) doc into the `new` file. 📋 
+ [x] Read the custom events API docs: https://plausible.io/docs/events-api to see what is possible in terms of _Advanced_ usage. Specifically can we submit an event with a _unique_ **`session_id`** to track a given "User" journey? 
+ [x] Please ***Comment*** below what is _possible_ in terms of events and _specifically_:
  + [x] What `Types` of data can be sent to the API
  + [x] What can be _displayed_ in the `Plausible Anlytics` UI without any customisation/modification. 
  + [x] Can we generate a `session_id` and submit it to the API with each event
  so that all pages for a given `User-Agent` are tied into a "Journey"?
  the `session_id` would be saved in `localStorage` and read before sending each event. 

If we end up having to build our own UI components, that's fine (and _expected_), 
we just want to see how far we can get with the built-in UI. 

# Bonus Level

+ [x] Refresh our understanding of Page Scroll Depth: https://github.com/dwyl/atm/issues/108
> **Note**: my understanding is that `Plausible` haven't implemented it yet. ⏳ 
+ [x] Write a basic script that calculates the page scroll depth.
+ [x] Log it to the custom events api TBD.

**Comment by LuchoTurtle** [comment]
There's a section on this -> https://github.com/dwyl/learn-analytics/tree/main/plausible#4-exploring-custom-events-in-plausible.

**Comment by nelsonic** [comment]
Yes, I saw that section before opening this issue. 👌 
Apologies for not referencing it before. 🤦‍♂️ 
Thank you for proactively adding it. 🙌 
It's a good starting point and can be used as the _basis_ for the `custom-events.md ` file. ✅ 

This is only _part_ of the `Analytics API` puzzle. 🧩
You see: what you've demonstrated here is logging a metric in _isolation_ ... 
What we _want_ to figure out: can we create a **`session`** for a given **`User-Agent`** (_anonymous_)
and track their "_journey_" through the site i.e: what was _their_ particular entry point, pages viewed and to what _depth_, searches performed, links clicked and eventual exit point; where were they when the stopped transmitting data?

Our current `Analytics` dashboard is not very _insightful_. 😕 
It's just boring **_aggregate_ stats** on page views, sources, locations and devices.

<img width="1014" alt="image" src="https://github.com/user-attachments/assets/67310c51-4dfe-46fa-8a91-c4139b376cdb">

<img width="504" alt="image" src="https://github.com/user-attachments/assets/cb6067d6-b073-47d3-9df1-20827555cce7">

<img width="505" alt="image" src="https://github.com/user-attachments/assets/5e1d1898-1f1f-4eb2-b82d-f32544f9f830">

<img width="504" alt="image" src="https://github.com/user-attachments/assets/246b5a07-aec1-4f18-9025-c988aa9408f1">

# _Boooooooring_ ... 🥱 

These stats are _good_ but they don't tell a ***story***. **So _what_**...? 🤷‍♀️ 

Once the PO/Executive has viewed the dashboard _once_
and though: "_Nice, but no **actionable insight**_" ... i.e. "_Meh_". 😒 
They are unlikely to `return` to the `Analytics` dashboard **_ever_ again**. 👎 
We've seen it _so many_ times before; we we've setup **`Google Analytics`** in 20+ orgs.
Unless the Executive/PO is _already_ super data-driven and asks questions, 🤓 ❓ 
they will look at the Analytics _once_ when you present it to them 1️⃣ 
and then ignore it for the next few _months_ because they're "too busy"... 💭 

I've re-written the OP/description above for clarity. 📝 ⬆️ 
Please comment with further clarifying questions until we're both on the same page as to what we're trying to achieve. 💬 🙏

**Comment by nelsonic** [comment]
@iteles FYI: this is the highest value task we can be doing because it will give the ***client*** value when they can see a "journey" through their product. 
All other work can be done - within reason - by a (competent) "intern" with an LLM. 
Writing *original* code for Analytics requires a human; for now ... ⏳

**Comment by LuchoTurtle** [comment]
Answering this issue:

- the [plausible.io/docs/events-api](https://plausible.io/docs/events-api) link that has provided has already been covered in the `[4-exploring-custom-events-in-plausible](https://github.com/dwyl/learn-analytics/tree/main/plausible#4-exploring-custom-events-in-plausible).` The link explores essentially the API requests (custom events/pageviews) that `next-plausible` under the hood already does.
- let me answer some questions:
	> `"What Types of data can be sent to the API?"`
	- it's like any other `json` file. As mentioned in [4-exploring-custom-events-in-plausible](https://github.com/dwyl/learn-analytics/tree/main/plausible#4-exploring-custom-events-in-plausible), we can send any type of properties alongside our event. We define it ourselves/
	> `"What can be displayed in the Plausible Anlytics UI without any customisation/modification?"`
	- great question. There's a [**funnel analysis**](https://plausible.io/docs/funnel-analysis) dashboard that we can add in the dashboard that essentially follows a "user journey" until conversion. We need to define what steps there are (these can be custom events *or* pageviews) until the conversion (which we also set). 
	> `Can we generate a session_id and submit it to the API with each event so that all pages for a given User-Agent are tied into a "Journey"?`
	- As far as I'm aware, with `Plausible` (perusing through their docs at https://plausible.io/docs), "advanced usage" only entails custom events, which we can define however we want and how/when they are created. `Plausible` will capture these and save them. However, custom display is not easily possible (without custom code). We **can** (as mentioned in the `exploring-custom-events-in-plausible` section) see these events in dashboards through goals and metrics. All of these "advanced features" are under the [`Events, funnels and e-commerce` section in their docs](https://plausible.io/docs/goal-conversions).
	All of this to say that, although we can certainly generate a `session_id` and send it with custom events, displaying them in a way that is useful may prove more difficult. This is why I'm a great proponent of giving the "funnel analysis" a try first (which has a dedicated away of viewing how/where are dropping throughout their "journey"), which is a *much quicker win* than fiddling with code from the `Plausible` Elixir instance.


So, here's what I'm hoping to document and implement in accordance to this issue:
- [x] create custom events related to **searching** and capturing it in `Plausible`.
- [x] create custom events related to **page scroll depth** and capturing it in `Plausible`.
- [x] create an example of funnel analysis to showcase user journeys.

**Comment by nelsonic** [comment]
@LuchoTurtle this is a good plan of action to make progress on this issue/task. Thanks. :shipit:
