### ISSUE TITLE
Chore: Document Deployment to an Azure VPS

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-analytics#9]
@LuchoTurtle if you still have an `Azure` account, please use your own account (credit card) and we will reimburse you.
If you don't have an account, LMK ASAP and I will add you to ours (which I will need to re-activate as we haven't used it in a couple of years ... ⏳) 

# Todo

+ [x] create `plausible/azure.md` file for documenting this. 🆕 
+ [x] Re-create the analytics deployment you've just done to `DigitalOcean` for `Azure` (what our client is using) 🧙‍♂️ 
+ [x] Document all the steps so that a _competent_ `DevOps` person can follow them. 📝 

Note: once you've successfully deployed, you can shut it all down to save cash. 
But we need to know it's working for work-work deployment. 👌

**Comment by LuchoTurtle** [comment]
I do not have an account (as I've mentioned in the standup yesterday). My personal Hotmail account got disabled due to inactivity. 💀

Am I deploying to a VM? Or am I doing kubernetes?

**Comment by nelsonic** [comment]
The VM is the easy path. `K8s` is total [overkill](https://github.com/dwyl/learn-docker/issues/24) for this. But it appears to be the preferred route for the client ... 🙃 
Please register for an `Azure` account (or re-activate) your account. 
the @dwyl one was closed (deleted by `MSFT` due to inactivity...! 🙄)
If `K8s` ends up being a rabbit hole, don't go down it, yet ...
Let the `work-work` `DevOps` person get as far as they can before you dive in.
